sudo: required
services:
  - docker

before_install:
  - docker build -t ionmocan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ionmocan/react-test npm test

after_success:
  - docker build -t ionmocan/multi-client ./client
  - docker build -t ionmocan/multi-nginx ./nging
  - docker build -t ionmocan/multi-server ./server
  - docker build -t ionmocan/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those imags and push them to docker hub
  - docker push ionmocan/multi-client
  - docker push ionmocan/multi-nginx
  - docker push ionmocan/multi-server
  - docker push ionmocan/multi-worker
